version: "3"
services:
  db:
    container_name: h2-actemo
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521" # TCP 포트 : H2 데이터베이스 서버
      - "8081:81" # HTTP 포트 : 웹콘솔 연결
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
  web:
    container_name: actemo-api-server
    image: smmin/actemo-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:1521/actemo
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db